name: sixtyten
favicon: null
layout_spectrum: 0.25088
typography_spectrum: 0.25
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f2f6f9'
    - '#00040f'
    - '#97afb9'
    - '#a18a79'
    - '#e3c7a2'
  brandStrength: 0.1875
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 1
purpose: []
