name: sixtyten
favicon: null
layout_spectrum: 0.5364059247076511
typography_spectrum: 0.6041788577567786
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.17999396892264485
  lightness: 0.1746259480714798
  saturation: 0.9103560142684728
  rhythmicContrast: 0.9585435146000236
purpose: []
